import React from "react";
import {Link} from "react-router-dom";
import Icon from "./Icon";
import {DataNotice,IS_UI_PREVIEW,useUi} from "./UiContext";
import rabbit from "../assets/jack-mining.png";
import pls from "../assets/pls.svg";
export default function MiningView(p){
 const {notify}=useUi();const ready=!IS_UI_PREVIEW&&p.currentWeek!==null&&!p.error;
 const disabled=p.loading||p.checkingAllowance;const hasAmount=Number(p.amount)>0&&Number.isFinite(Number(p.amount));
 const stats=[['clock','Current week',ready?`#${p.currentWeek}`:'—','Weekly participation window'],['coin','Weekly JACK pool',ready?p.formattedWeeklyPool:'—','Confirmed network data'],['pickaxe','Your points',ready?p.formattedPoints:'—','Amount × participation time'],['leaf','Your pool share',ready?p.formattedShareThisWeek:'—','A share, not a fixed return']];
 return <div className="jr-page"><div className="jr-container">
 <section className="jr-feature-hero jr-mining-hero"><div><span className="jr-eyebrow">THE MINING HUB / WEEKLY WINDOWS</span><h1>Make your next move.<br/><span>Mine JACK.</span></h1><p>One weekly window. One fee token. Explore how participation points connect to your share of JACK rewards.</p><Link className="jr-text-link" to="/mining/claims">View your miners & claims <Icon size={17}/></Link></div><img src={rabbit} alt="Jack Rabbit mining for gold"/></section>
 <div className="jr-stats">{stats.map(([icon,label,value,note])=><article className="jr-kpi" key={label}><span className="jr-round-icon"><Icon name={icon}/></span><div><span>{label}</span><strong>{value}</strong><small>{note}</small></div></article>)}</div>
 <div className="jr-two-column"><section className="jr-panel jr-miner-form"><div className="jr-panel-header"><div><h2>Deploy your miner</h2><p>Your next hop into the weekly reward pool.</p></div><span className={`jr-badge ${!ready?'jr-badge-amber':''}`}><Icon name={ready?'check':'clock'} size={13}/>{ready?(p.miningOpen?'Window open':'Window closed'):'Awaiting network'}</span></div>
 <ol className="jr-form-steps"><li className="active"><span>1</span>Choose amount</li><li><span>2</span>Review</li><li><span>3</span>Deploy</li></ol>
 <label className="jr-field-label" htmlFor="jr-miner-amount">Mining contribution <span>{ready?p.feeTokenLabel:'Fee token loads from the network'}</span></label>
 <div className="jr-input-box"><div className="jr-amount-row"><input id="jr-miner-amount" inputMode="decimal" autoComplete="off" placeholder="0.00" value={p.amount} onChange={e=>{if(/^\d*\.?\d*$/.test(e.target.value))p.setAmount(e.target.value);}} aria-describedby="jr-mining-amount-help"/><span className="jr-token-pill"><img src={ready?p.feeTokenIconSrc:pls} alt=""/>{ready?p.feeTokenLabel:'PLS'}{!ready&&<small>preview</small>}</span></div><div className="jr-amount-caption"><span>Wallet balance: —</span><span>Confirm before signing</span></div></div>
 <p id="jr-mining-amount-help" className="jr-form-note">Enter the contribution you want to review. Network fees and reward eligibility must be confirmed before any transaction.</p>
 <dl className="jr-summary-list"><div><dt>Week</dt><dd>{ready?`#${p.currentWeek}`:'Not loaded'}</dd></div><div><dt>Window closes in</dt><dd>{ready?p.formattedTimeLeft:'—'}</dd></div><div><dt>Estimated JACK</dt><dd>{ready?`${p.formattedJack} JACK`:'Available after connection'}</dd></div><div><dt>Token approval</dt><dd>{ready?(p.needsApproval?'Required':p.feeTokenAddress==='0x0000000000000000000000000000000000000000'?'Not required for native PLS':'Checked'):'Checked at review'}</dd></div></dl>
 <hr className="jr-divider"/>
 {p.needsApproval&&<button className="jr-btn jr-btn-outline jr-btn-wide" data-transaction="Approve mining contribution" onClick={p.handleApprove} disabled={disabled}>Approve {p.feeTokenLabel}<Icon name="shield"/></button>}
 <button className="jr-btn jr-btn-dark jr-btn-wide" data-transaction="Review miner deployment" onClick={p.handleDeploy} disabled={disabled||!hasAmount||(!IS_UI_PREVIEW&&(!ready||!p.miningOpen))}>{disabled?'Loading…':'Review deployment'}<Icon/></button>
 {!IS_UI_PREVIEW&&p.error&&<p role="alert" className="jr-error-text">{p.error}</p>}
 <div className="jr-form-assurance"><Icon name="shield" size={15}/>{IS_UI_PREVIEW?'UI preview. No approvals or transactions will be requested.':'Always review the network and amount in your wallet.'}</div>
 </section>
 <aside className="jr-stack"><section className="jr-panel jr-pool-panel"><div className="jr-panel-header"><h2>This week’s pool</h2><Icon name="coin"/></div><div className="jr-pool-number">{ready?p.formattedWeeklyPool:'—'}<span>JACK</span></div><div className="jr-progress" role="progressbar" aria-label="Weekly reward pool funding" aria-valuemin={0} aria-valuemax={100} aria-valuenow={ready?p.weeklyPoolPercent:0}><i style={{width:ready?`${p.weeklyPoolPercent}%`:'0%'}}/></div><div className="jr-amount-caption"><span>{ready?`${p.formattedWeeklyPoolPercent}% of weekly cap`:'Funding data not loaded'}</span><span>{ready?`${p.formattedWeeklyCap} cap`:'—'}</span></div><dl className="jr-summary-list"><div><dt>Fees collected</dt><dd>{ready?`${p.formattedTotalFees} ${p.feeTokenLabel}`:'—'}</dd></div><div><dt>Future-week reserve</dt><dd>{ready?`${p.formattedReserveFutureWeeks} JACK`:'—'}</dd></div></dl><button className="jr-btn jr-btn-outline jr-btn-wide" onClick={()=>IS_UI_PREVIEW?notify('Preview mode: network reads are not running.'):p.handleSyncWeek()} disabled={disabled}><Icon name="refresh" size={17}/> Refresh week</button></section>
 <section className="jr-panel jr-how-panel"><span className="jr-eyebrow">BEFORE YOU DIG IN</span><h2>Every point has a purpose.</h2><div className="jr-flow-list">{[['1','Join a weekly window','The active window determines the fee token.'],['2','Build participation points','Points depend on contribution and time remaining.'],['3','Return to claim','Check finalized weeks in Your miners & claims.']].map(([n,t,d])=><div key={n}><span>{n}</span><section><h3>{t}</h3><p>{d}</p></section></div>)}</div><Link to="/mining/claims" className="jr-text-link">See the claims page <Icon size={17}/></Link></section></aside></div>
 <DataNotice>{IS_UI_PREVIEW?'This design preview intentionally leaves live balances and rewards blank. Existing mining contract handlers are preserved but cannot be triggered here.':'Rewards depend on the active window and verified contract state. Estimates are not guaranteed returns.'}</DataNotice>
 <section className="jr-panel jr-mining-faq"><div className="jr-panel-header"><h2>A few things worth knowing</h2><span className="jr-eyebrow">MINING BASICS</span></div><div className="jr-faq-list"><details><summary>When can rewards be claimed?<Icon name="chevron"/></summary><p>Eligible rewards are claimed after the relevant week is finalized. Open Your miners & claims to review a position. Final behavior must match the deployed mining contract.</p></details><details><summary>What happens if a window is closed?<Icon name="chevron"/></summary><p>Do not submit a contribution. Refresh the window and check its funding and pause state before continuing.</p></details><details><summary>How is Treasury funding handled?<Icon name="chevron"/></summary><p>Funding must follow the methods supported by the verified mining contract. The current UI integration is still being checked.</p><button className="jr-btn jr-btn-outline jr-btn-small" data-transaction="Treasury funding request" onClick={p.handleTryFunding}>Review funding action <Icon size={15}/></button></details></div></section>
 </div></div>;
}
