import React from "react";
import {Link,useLocation} from "react-router-dom";
import Icon from "./Icon";
import {DataNotice,IS_UI_PREVIEW,PageHeading} from "./UiContext";
export default function StakingFrame({children}){
 const {pathname}=useLocation();const jackies=pathname.includes('jackies');
 return <div className="jr-staking-frame"><div className="jr-container"><PageHeading eyebrow={jackies?'STAKING / JACK STAKERS':'STAKING / EXTERNAL STAKERS'} title={jackies?'Your JACK. Your place in the burrow.':'Stake what you believe in.'} description={jackies?'Keep your JACK position and external-token rewards in one view.':'Explore the external-token pools and their JACK reward streams.'} action={<Link to="/#how-it-works" className="jr-btn jr-btn-outline"><Icon name="book" size={17}/> How it fits together</Link>}/>{IS_UI_PREVIEW&&<DataNotice>Wallet interactions are paused in this design preview. The existing staking and reward handlers are preserved for verified network testing.</DataNotice>}</div>
 <div className="jr-staking-body">{children}</div>
 <section className="jr-container jr-panel jr-staking-help"><div className="jr-panel-header"><h2>A clearer staking journey.</h2><Icon name="shield"/></div><div className="jr-faq-list"><details><summary>What’s the difference between the staking areas?<Icon name="chevron"/></summary><p>External stakers explore non-JACK token pools with JACK rewards. JACK stakers use the JACK position and its configured external reward streams. The deployed contract determines the supported pools and actual reward behavior.</p></details><details><summary>Why are no balances or pools shown in the preview?<Icon name="chevron"/></summary><p>The interface does not invent wallet holdings. These readouts need a verified network connection and matching contract interfaces. Wallet access is disabled while reviewing this design.</p></details><details><summary>What should I check before a real stake?<Icon name="chevron"/></summary><p>Confirm the network, pool token, amount, approval request, and transaction details. Staking and token values involve risk; this preview is not a production release or a security audit.</p></details></div></section></div>;
}
