import React,{useMemo,useState} from "react";
import {Link,useNavigate} from "react-router-dom";
import Icon from "../ui/Icon";
import {DataNotice,useUi} from "../ui/UiContext";
import {usePreviewPortfolio,displayAmount,dateAfter} from "../ui/PreviewPortfolio";
import {RISKY_BONDS} from "./NFTBonds";
import rabbit from "../assets/jackfallingrabbithole.png";
import pdai from "../assets/pdai.svg";
import collectible from "../assets/KingJack.png";
export default function BondMintExperience(){
 const {show,close,notify}=useUi();const {addBond}=usePreviewPortfolio();const navigate=useNavigate();
 const [amount,setAmount]=useState('1000');const [date,setDate]=useState(()=>dateAfter(365));const [swept,setSwept]=useState([]);
 const today=useMemo(()=>{const d=new Date();d.setHours(12,0,0,0);return d;},[]);
 const days=Math.round((new Date(`${date}T12:00:00`)-today)/86400000);const value=Number(amount);const premium=Math.max(0,Math.min(25,(days-180)/(1825-180)*25));const base=value*4.25;const total=base*(1+premium/100);
 const valid=Number.isFinite(value)&&value>0&&value<=82450&&Number.isFinite(days)&&days>=180&&days<=1825;
 const help=!amount?'Enter a pDAI amount.':!Number.isFinite(value)||value<=0?'Enter a valid positive amount.':value>82450?'Amount exceeds the example balance.':!Number.isFinite(days)||days<180||days>1825?'Choose a term between 180 and 1,825 days.':'';
 function review(e){e.preventDefault();if(!valid)return;show({eyebrow:'EXAMPLE BOND · NO REAL DEPOSIT',title:'Your next chapter, in review.',body:<><div className="jr-dialog-amount">{displayAmount(value)} pDAI</div><dl className="jr-summary-list"><div><dt>Example JACK estimate</dt><dd>{displayAmount(total)} JACK</dd></div><div><dt>Term</dt><dd>{days} days</dd></div><div><dt>Example unlock date</dt><dd>{date}</dd></div><div><dt>Wallet approval</dt><dd>Not requested</dd></div></dl><DataNotice>This adds a sample position to My Bonds. It does not create an NFT or deposit tokens.</DataNotice></>,actions:<><button className="jr-btn jr-btn-outline" onClick={close}>Back</button><button className="jr-btn jr-btn-dark" onClick={()=>{addBond({pdai:value,jack:total,baseJack:base,twap:4.25,days,maturity:date,premium});close();notify('Sample bond added. No tokens were deposited.');navigate('/nfts/bonds');}}>Add preview bond <Icon/></button></>});}
 function sweep(b){show({eyebrow:'EXAMPLE EXPIRED BOND',title:`Review ${b.id} cleanup.`,body:<><p>This previews an expired position leaving the cleanup list. Live eligibility, permissions, and contract behavior must be verified separately.</p><DataNotice>No NFT will be burned and no funds will move.</DataNotice></>,actions:<><button className="jr-btn jr-btn-outline" onClick={close}>Cancel</button><button className="jr-btn jr-btn-dark" onClick={()=>{setSwept(ids=>[...ids,b.id]);close();notify('Example cleanup recorded. No contract action was sent.');}}>Simulate cleanup <Icon/></button></>});}
 return <div className="jr-page"><div className="jr-container"><section className="jr-feature-hero jr-bond-hero"><div><span className="jr-eyebrow">JACK BARROW / BOND NFTS</span><h1>Take the longer view.<br/><span>Explore Bond NFTs.</span></h1><p>Choose an amount, explore a term, and see how your position could take shape. A new way into the pDAI story.</p><Link className="jr-text-link" to="/nfts/bonds">Explore your bond positions <Icon size={16}/></Link></div><img src={rabbit} alt="Jack Rabbit leaping into a new chapter"/></section>
 <DataNotice>Bond pricing, balances, capacity, and positions are illustrative. Contract integration is not enabled.</DataNotice>
 <div className="jr-two-column"><form className="jr-panel" onSubmit={review}><div className="jr-panel-header"><div><h2>Build your bond</h2><p>Your amount. Your timeline. A clearer review.</p></div><span className="jr-badge jr-badge-amber">UI preview</span></div><ol className="jr-form-steps"><li className="active"><span>1</span>Amount</li><li className="active"><span>2</span>Term</li><li><span>3</span>Review</li></ol>
 <label className="jr-field-label" htmlFor="jr-bond-amount">pDAI amount <span>Example balance: 82,450 pDAI</span></label><div className="jr-input-box"><div className="jr-amount-row"><input id="jr-bond-amount" inputMode="decimal" value={amount} onChange={e=>/^\d*\.?\d*$/.test(e.target.value)&&setAmount(e.target.value)} placeholder="0.00"/><span className="jr-token-pill"><img src={pdai} alt=""/>pDAI</span></div><div className="jr-amount-caption"><span>Example quote: 1 pDAI = 4.25 JACK</span><button type="button" onClick={()=>setAmount('82450')}>MAX</button></div></div>
 <div className="jr-form-spacer"/><label className="jr-field-label" htmlFor="jr-bond-date">Choose your term <span>180–1,825 days</span></label><div className="jr-term-options">{[[180,'180 days'],[365,'1 year'],[730,'2 years'],[1825,'5 years']].map(([n,label])=><button type="button" key={n} className={days===n?'active':''} aria-pressed={days===n} onClick={()=>setDate(dateAfter(n))}>{label}</button>)}</div><input className="jr-date-input" id="jr-bond-date" type="date" min={dateAfter(180)} max={dateAfter(1825)} value={date} onChange={e=>setDate(e.target.value)}/>
 <dl className="jr-summary-list"><div><dt>Example base quote</dt><dd>{displayAmount(Number.isFinite(base)?base:0)} JACK</dd></div><div><dt>Illustrative term premium</dt><dd>{Number.isFinite(premium)?premium.toFixed(2):'0.00'}%</dd></div><div><dt>Example total estimate</dt><dd>{displayAmount(Number.isFinite(total)?total:0)} JACK</dd></div></dl>{help&&<p className="jr-error-text" role="alert">{help}</p>}<button className="jr-btn jr-btn-dark jr-btn-wide" disabled={!valid}>Review bond <Icon/></button><p className="jr-form-assurance"><Icon name="shield" size={15}/> Preview only. No token approval is requested.</p></form>
 <aside className="jr-stack"><section className="jr-panel jr-collectible-panel"><div className="jr-panel-header"><div><span className="jr-eyebrow">A POSITION WITH PERSONALITY</span><h2>Your future collectible.</h2></div><Icon name="star"/></div><div className="jr-nft-art"><span>JACK BARROW</span><img src={collectible} alt="Golden JACK collectible illustration"/><div>BOND NFT <small>ILLUSTRATIVE ARTWORK</small></div></div><p className="jr-form-note">Each real position will be tied to its verified contract terms. This image is an interface illustration, not a minted asset.</p></section><section className="jr-panel"><h2>Time, with a clearer view.</h2><div className="jr-flow-list">{[['1','Choose your contribution','Start with the amount you want to explore.'],['2','Choose a term','Compare the example timeline and premium.'],['3','Track the position','Preview your bond in the positions gallery.']].map(([n,t,d])=><div key={n}><span>{n}</span><section><h3>{t}</h3><p>{d}</p></section></div>)}</div><Link className="jr-text-link" to="/nfts/bonds">Open My Bonds <Icon size={16}/></Link></section></aside></div>
 <section className="jr-panel jr-cleanup-panel"><div className="jr-panel-header"><div><span className="jr-eyebrow">EXPIRED BOND CLEANUP</span><h2>A place for the unfinished.</h2><p>Review example positions beyond their claim grace period.</p></div><span className="jr-badge jr-badge-amber">Sample data</span></div><div className="jr-table-scroll"><table className="jr-table"><thead><tr><th>Example bond</th><th>Example owner</th><th>Unclaimed JACK</th><th>Example grace end</th><th>Action</th></tr></thead><tbody>{RISKY_BONDS.filter(b=>!swept.includes(b.id)).map(b=><tr key={b.id}><td><strong>{b.id}</strong></td><td>{b.owner}</td><td>{displayAmount(b.unclaimedJack)} JACK</td><td>{b.graceEnded}</td><td><button className="jr-btn jr-btn-outline jr-btn-small" onClick={()=>sweep(b)}>Review cleanup <Icon size={14}/></button></td></tr>)}{swept.length===RISKY_BONDS.length&&<tr><td colSpan="5"><div className="jr-empty"><Icon name="check" size={28}/><h3>Example cleanup complete.</h3><p>No real bonds were affected.</p></div></td></tr>}</tbody></table></div><DataNotice>Real cleanup requires verified eligibility and the correct contract permissions.</DataNotice></section>
 </div></div>;}
