import React,{useMemo,useState} from "react";
import {Link} from "react-router-dom";
import {isAddress,ZeroAddress} from "ethers";
import Icon from "../ui/Icon";
import {DataNotice,EmptyState,PageHeading,useUi} from "../ui/UiContext";
import {usePreviewPortfolio,displayAmount} from "../ui/PreviewPortfolio";
import artwork from "../assets/KingJack.png";
function TransferForm({bond}){
 const {updateBond}=usePreviewPortfolio();const {close,notify}=useUi();const [recipient,setRecipient]=useState('');const [error,setError]=useState('');
 function submit(e){e.preventDefault();const address=recipient.trim();if(!isAddress(address)||address.toLowerCase()===ZeroAddress){setError('Enter a valid, non-zero wallet address for this preview.');return;}updateBond(bond.id,{status:'Transferred',previewRecipient:address});close();notify('Example transfer recorded. No NFT was sent.');}
 return <form onSubmit={submit}><p>Explore the transfer review for <strong>{bond.id}</strong>.</p><label className="jr-field-label" htmlFor="jr-nft-recipient">Recipient address</label><input id="jr-nft-recipient" className="jr-text-input" value={recipient} onChange={e=>{setRecipient(e.target.value);setError('');}} placeholder="0x…" autoComplete="off" spellCheck={false}/>{error&&<p className="jr-error-text" role="alert">{error}</p>}<DataNotice>This changes a sample position only. No wallet signature or NFT transfer is requested.</DataNotice><button className="jr-btn jr-btn-dark jr-btn-wide">Simulate transfer <Icon/></button></form>;
}
export default function BondPositionsExperience(){
 const {bonds,updateBond}=usePreviewPortfolio();const {show,close,notify}=useUi();const [search,setSearch]=useState('');const [filter,setFilter]=useState('all');const [view,setView]=useState('grid');const [samples,setSamples]=useState(true);
 const claimable=b=>['Claimable','Matured'].includes(b.status);
 const rows=useMemo(()=>samples?bonds.filter(b=>`${b.id} ${b.status}`.toLowerCase().includes(search.toLowerCase())&&(filter==='all'||(filter==='active'&&b.status==='Active')||(filter==='claimable'&&['Claimable','Matured'].includes(b.status))||(filter==='history'&&['Claimed','Transferred'].includes(b.status)))):[],[bonds,search,filter,samples]);
 function details(b){show({eyebrow:'EXAMPLE BOND POSITION',title:b.id,body:<><div className="jr-dialog-amount">{displayAmount(b.jack)} JACK</div><dl className="jr-summary-list"><div><dt>Example contribution</dt><dd>{displayAmount(b.pdai)} pDAI</dd></div><div><dt>Term</dt><dd>{b.days} days</dd></div><div><dt>Example maturity</dt><dd>{b.maturity}</dd></div><div><dt>Preview status</dt><dd>{b.status}</dd></div></dl><DataNotice>This position is not an on-chain NFT.</DataNotice></>});}
 function claim(b){show({eyebrow:'EXAMPLE CLAIM REVIEW',title:'Ready for the next chapter?',body:<><div className="jr-dialog-amount">{displayAmount(b.jack)} JACK</div><p>Preview claiming bond {b.id}. The position will move to History in this session.</p><DataNotice>No JACK will be transferred.</DataNotice></>,actions:<><button className="jr-btn jr-btn-outline" onClick={close}>Cancel</button><button className="jr-btn jr-btn-dark" onClick={()=>{updateBond(b.id,{status:'Claimed'});close();notify('Example bond claimed. No tokens were transferred.');}}>Simulate claim <Icon/></button></>});}
 function transfer(b){show({eyebrow:'PREVIEW NFT TRANSFER',title:'A new home for this bond.',body:<TransferForm bond={b}/>,actions:<span className="jr-note">Example position only.</span>});}
 const actions=b=><div className="jr-bond-actions"><button className="jr-btn jr-btn-dark jr-btn-small" onClick={()=>claimable(b)?claim(b):details(b)}>{claimable(b)?'Review claim':'View details'}<Icon size={14}/></button>{!['Claimed','Transferred'].includes(b.status)&&<button className="jr-icon-btn" onClick={()=>transfer(b)} aria-label={`Transfer ${b.id}`}><Icon name="external" size={17}/></button>}</div>;
 return <div className="jr-page"><div className="jr-container"><PageHeading eyebrow="JACK BARROW / MY BONDS" title="Your bonds. Your timeline." description="A gallery of positions, with the details and next steps always close at hand." action={<Link className="jr-btn jr-btn-dark" to="/nfts">Create a bond <Icon/></Link>}/>
 <div className="jr-stats">{[['book','Example positions',samples?bonds.length:'—'],['lock','Example active',samples?bonds.filter(b=>b.status==='Active').length:'—'],['coin','Example claimable',samples?bonds.filter(claimable).length:'—'],['check','Preview history',samples?bonds.filter(b=>['Claimed','Transferred'].includes(b.status)).length:'—']].map(([icon,label,value])=><article className="jr-kpi" key={label}><span className="jr-round-icon"><Icon name={icon}/></span><div><span>{label}</span><strong>{value}</strong><small>Not a wallet holding</small></div></article>)}</div>
 <DataNotice>These are sample positions. Bonds added from the Mint preview appear here for this session; reloading resets the examples.</DataNotice>
 <div className="jr-toolbar"><div className="jr-tabs" role="group" aria-label="Filter bond positions">{[['all','All bonds'],['active','Active'],['claimable','Claimable'],['history','History']].map(([id,label])=><button key={id} className={filter===id?'active':''} aria-pressed={filter===id} onClick={()=>setFilter(id)}>{label}</button>)}</div><div className="jr-toolbar-group"><label className="jr-search"><Icon name="search" size={17}/><input aria-label="Search bond positions" placeholder="Search bond ID or status…" value={search} onChange={e=>setSearch(e.target.value)}/></label><div className="jr-tabs"><button className={view==='grid'?'active':''} onClick={()=>setView('grid')} aria-label="Bond gallery view" aria-pressed={view==='grid'}><Icon name="grid" size={17}/></button><button className={view==='list'?'active':''} onClick={()=>setView('list')} aria-label="Bond list view" aria-pressed={view==='list'}><Icon name="list" size={17}/></button></div></div></div>
 {!rows.length?<section className="jr-panel"><EmptyState icon="book" title={search?'No bonds match your search.':'A new chapter starts here.'} action={<Link className="jr-btn jr-btn-dark" to="/nfts">Explore a bond <Icon/></Link>}>{samples?'Try another filter, or create a sample bond to explore the full interface journey.':'There are no connected wallet positions in this UI preview.'}</EmptyState></section>:view==='grid'?<div className="jr-bonds-grid">{rows.map((b,i)=><article className="jr-bond-card" key={b.id}><div className={`jr-bond-art jr-bond-art-${i%3}`}><span className="jr-bond-edition">JACK BARROW / EXAMPLE</span><img src={artwork} alt={`Illustration for example bond ${b.id}`}/><span className="jr-bond-art-id">{b.id}</span><span className="jr-bond-seal"><Icon name="shield" size={17}/></span></div><div className="jr-bond-card-body"><div className="jr-panel-header"><h2>{b.id}</h2><span className={`jr-badge ${b.status==='Active'?'jr-badge-amber':''}`}>{b.status}</span></div><div className="jr-bond-value">{displayAmount(b.jack)} <span>JACK</span></div><span className="jr-data-label">EXAMPLE POSITION VALUE</span><dl className="jr-summary-list"><div><dt>Example pDAI</dt><dd>{displayAmount(b.pdai)}</dd></div><div><dt>Term</dt><dd>{b.days} days</dd></div><div><dt>Example unlock</dt><dd>{b.maturity}</dd></div></dl>{actions(b)}</div></article>)}</div>:<section className="jr-panel"><div className="jr-table-scroll"><table className="jr-table"><thead><tr><th>Example bond</th><th>pDAI</th><th>Example JACK</th><th>Unlock date</th><th>Status</th><th>Actions</th></tr></thead><tbody>{rows.map(b=><tr key={b.id}><td><strong>{b.id}</strong><small className="jr-table-sub">{b.days}-day term</small></td><td>{displayAmount(b.pdai)}</td><td>{displayAmount(b.jack)}</td><td>{b.maturity}</td><td><span className="jr-badge">{b.status}</span></td><td>{actions(b)}</td></tr>)}</tbody></table></div></section>}
 <div className="jr-table-footer"><span>{rows.length} example {rows.length===1?'position':'positions'} shown</span><button className="jr-btn jr-btn-outline jr-btn-small" onClick={()=>setSamples(!samples)}>{samples?'Hide sample positions':'Show sample positions'}</button></div><section className="jr-next-step"><Icon name="shield"/><p>Bond eligibility and ownership must come from the final verified contracts. All actions on this page update examples only.</p><Link to="/nfts" className="jr-text-link">Explore the mint flow <Icon size={16}/></Link></section>
 </div></div>;}
