import React,{useMemo,useState} from "react";
import {Link} from "react-router-dom";
import {liveMiners,claimMiners} from "./WeekClaims";
import Icon from "../ui/Icon";
import {DataNotice,EmptyState,PageHeading,useUi} from "../ui/UiContext";
const amount=v=>Number.parseFloat(String(v).replace(/,/g,''))||0;
const fmt=n=>n.toLocaleString(undefined,{maximumFractionDigits:2});
export default function ClaimsExperience(){
 const {show,close,notify}=useUi();const [tab,setTab]=useState('live');const [search,setSearch]=useState('');const [page,setPage]=useState(0);const [claimed,setClaimed]=useState([]);const [samples,setSamples]=useState(true);
 const claimable=claimMiners.filter(m=>!claimed.includes(m.id));const estimated=liveMiners.reduce((n,m)=>n+amount(m.reward),0);const total=claimable.reduce((n,m)=>n+amount(m.reward),0);
 const rows=useMemo(()=>{const all=tab==='live'?liveMiners:tab==='claimable'?claimMiners.filter(m=>!claimed.includes(m.id)):claimMiners.filter(m=>claimed.includes(m.id));return samples?all.filter(m=>`${m.id} ${m.week} ${m.mode}`.toLowerCase().includes(search.toLowerCase())):[];},[tab,claimed,search,samples]);
 const pages=Math.max(1,Math.ceil(rows.length/6));const current=Math.min(page,pages-1);const visible=rows.slice(current*6,current*6+6);
 function previewClaim(items){const sum=items.reduce((n,m)=>n+amount(m.reward),0);show({eyebrow:'EXAMPLE CLAIM · NO REAL FUNDS',title:items.length===1?'Review this claim.':'Review all example claims.',body:<><div className="jr-dialog-amount">{fmt(sum)} JACK</div><p>{items.length} example {items.length===1?'position':'positions'} selected. This will only move sample positions into the History tab.</p><DataNotice>Claim transactions are not implemented in this preview.</DataNotice></>,actions:<><button className="jr-btn jr-btn-outline" onClick={close}>Cancel</button><button className="jr-btn jr-btn-dark" onClick={()=>{setClaimed(ids=>[...new Set([...ids,...items.map(m=>m.id)])]);close();notify('Example claim recorded. No real JACK was transferred.');}}>Simulate claim <Icon/></button></>});}
 function changeTab(t){setTab(t);setPage(0);}
 return <div className="jr-page"><div className="jr-container"><PageHeading eyebrow="MINING / YOUR POSITIONS" title="Every miner. Every milestone." description="Follow active windows, review claimable rewards, and keep a clear history of your participation." action={<Link className="jr-btn jr-btn-dark" to="/mining">Deploy a miner <Icon/></Link>}/>
 <div className="jr-stats">{[['pickaxe','Example live miners',samples?liveMiners.length:'—'],['coin','Estimated example rewards',samples?`${fmt(estimated)} JACK`:'—'],['wallet','Example claimable',samples?`${fmt(total)} JACK`:'—'],['check','Preview claims recorded',samples?claimed.length:'—']].map(([icon,label,value])=><article key={label} className="jr-kpi"><span className="jr-round-icon"><Icon name={icon}/></span><div><span>{label}</span><strong>{value}</strong><small>Interface sample only</small></div></article>)}</div>
 <DataNotice>The positions and rewards here are examples. Claims update this preview only, not your wallet.</DataNotice>
 <section className="jr-panel"><div className="jr-panel-header"><div><h2>Your mining activity</h2><p>A place for each step of the weekly journey.</p></div><button className="jr-btn jr-btn-outline jr-btn-small" onClick={()=>{setSamples(!samples);setPage(0);}}>{samples?'Hide sample data':'Show sample data'}</button></div>
 <div className="jr-toolbar"><div className="jr-tabs" role="group" aria-label="Mining position status">{[['live','Live miners'],['claimable','Ready to claim'],['history','History']].map(([id,label])=><button key={id} className={tab===id?'active':''} onClick={()=>changeTab(id)} aria-pressed={tab===id}>{label}</button>)}</div><label className="jr-search"><Icon name="search" size={17}/><input aria-label="Search mining positions" value={search} onChange={e=>{setSearch(e.target.value);setPage(0);}} placeholder="Search ID, week, or mode…"/></label></div>
 {!visible.length?<EmptyState icon={tab==='history'?'clock':'pickaxe'} title={search?'No matching miners':tab==='history'?'Your story is just beginning.':'No positions to display.'} action={<button className="jr-btn jr-btn-outline" onClick={()=>{setSearch('');setSamples(true);changeTab('live');}}>Explore sample miners <Icon/></button>}>{samples?'Try a different filter, or preview a claim to see it appear in History.':'A connected wallet’s verified positions will appear here after integration. You can still explore the sample UI.'}</EmptyState>:<div className="jr-table-scroll"><table className="jr-table"><thead><tr><th>Miner / week</th><th>Mode</th><th>Your points</th><th>{tab==='live'?'Estimated reward':'Example reward'}</th><th>Status</th><th><span className="jr-sr-only">Action</span></th></tr></thead><tbody>{visible.map(m=><tr key={`${tab}-${m.id}`}><td><div className="jr-table-identity"><span className="jr-round-icon"><Icon name="pickaxe" size={19}/></span><div><strong>Miner {m.id}</strong><small>{m.week}</small></div></div></td><td><span className="jr-mode"><Icon name={m.mode==='Organic'?'leaf':'shield'} size={15}/>{m.mode}</span></td><td>{m.points}</td><td><strong>{fmt(amount(m.reward))} JACK</strong></td><td><span className={`jr-badge ${tab==='live'?'jr-badge-amber':''}`}>{tab==='live'?'Example live':tab==='claimable'?'Example claimable':'Preview claimed'}</span></td><td>{tab==='claimable'?<button className="jr-btn jr-btn-dark jr-btn-small" onClick={()=>previewClaim([m])}>Review claim <Icon size={15}/></button>:<span className="jr-note">{tab==='live'?m.timeAccrued:'Recorded in preview'}</span>}</td></tr>)}</tbody></table></div>}
 <div className="jr-table-footer"><span>{rows.length?`${current*6+1}–${Math.min((current+1)*6,rows.length)} of ${rows.length} example positions`:'No results'}</span><nav className="jr-pagination" aria-label="Mining positions pagination"><button className="jr-icon-btn" onClick={()=>setPage(Math.max(0,current-1))} disabled={current===0} aria-label="Previous page">←</button><span>{current+1} / {pages}</span><button className="jr-icon-btn" onClick={()=>setPage(Math.min(pages-1,current+1))} disabled={current+1>=pages} aria-label="Next page">→</button></nav>{tab==='claimable'&&<button className="jr-btn jr-btn-dark jr-btn-small" onClick={()=>previewClaim(claimable)} disabled={!samples||!claimable.length}>Review all claims <Icon size={15}/></button>}</div>
 </section><section className="jr-next-step"><Icon name="info" size={19}/><p>Rewards become claimable according to the verified mining contract. Sample statuses shown here are for design review, not on-chain eligibility.</p><Link to="/mining" className="jr-text-link">Back to the hub <Icon size={16}/></Link></section></div></div>;
}
