import React,{useMemo,useState} from "react";
import {Link} from "react-router-dom";
import {INITIAL_FARMS,TOKEN_META} from "./farms";
import Icon from "../ui/Icon";
import {DataNotice,EmptyState,useUi} from "../ui/UiContext";
import rabbit from "../assets/richrabbit.png";
import jack from "../assets/jacklogo.png";
function FarmForm({farm,onUpdate}){
 const {close,notify}=useUi();const [mode,setMode]=useState('stake');const [amount,setAmount]=useState('');const [error,setError]=useState('');
 const available=mode==='stake'?farm.balance:farm.stakedLp;
 function submit(e){e.preventDefault();const n=Number(amount);if(!Number.isFinite(n)||n<=0||n>available){setError(`Enter an amount greater than zero and no more than ${available.toFixed(4)} LP.`);return;}onUpdate(farm.id,n,mode);close();notify(`Preview ${mode} updated. No transaction was sent.`);}
 return <form onSubmit={submit}><div className="jr-tabs" role="group" aria-label="Position action">{['stake','unstake'].map(t=><button type="button" key={t} className={mode===t?'active':''} onClick={()=>{setMode(t);setAmount('');setError('');}}>{t==='stake'?'Stake LP':'Unstake LP'}</button>)}</div><div className="jr-form-spacer"/><label className="jr-field-label" htmlFor="jr-farm-amount">LP amount <span>Preview balance: {available.toFixed(4)}</span></label><div className="jr-input-box"><div className="jr-amount-row"><input id="jr-farm-amount" inputMode="decimal" value={amount} onChange={e=>{if(/^\d*\.?\d*$/.test(e.target.value)){setAmount(e.target.value);setError('');}}} placeholder="0.00"/><span className="jr-token-pill">LP</span></div></div><div className="jr-quick-amounts">{[25,50,75,100].map(v=><button key={v} type="button" onClick={()=>setAmount(String(Number((available*v/100).toFixed(6))))}>{v===100?'MAX':`${v}%`}</button>)}</div><dl className="jr-summary-list"><div><dt>Pool</dt><dd>{farm.pair}</dd></div><div><dt>Preview position</dt><dd>{farm.stakedLp.toFixed(4)} LP</dd></div><div><dt>Network transaction</dt><dd>None</dd></div></dl>{error&&<p role="alert" className="jr-error-text">{error}</p>}<button className="jr-btn jr-btn-dark jr-btn-wide" type="submit">Simulate {mode}<Icon/></button></form>;
}
export default function FarmsExperience(){
 const {show,close,notify}=useUi();const [rows,setRows]=useState(()=>INITIAL_FARMS.map(f=>({...f})));const [filter,setFilter]=useState('all');const [search,setSearch]=useState('');const [view,setView]=useState('grid');const [sort,setSort]=useState('default');const [favorites,setFavorites]=useState([]);
 const visible=useMemo(()=>{let r=rows.filter(f=>f.pair.toLowerCase().includes(search.toLowerCase())&&(filter!=='staked'||f.stakedLp>0)&&(filter!=='favorites'||favorites.includes(f.id)));if(sort==='apr')r.sort((a,b)=>parseFloat(b.apr)-parseFloat(a.apr));if(sort==='name')r.sort((a,b)=>a.pair.localeCompare(b.pair));return r;},[rows,search,filter,favorites,sort]);
 function update(id,n,mode){setRows(current=>current.map(f=>f.id!==id?f:{...f,stakedLp:f.stakedLp+(mode==='stake'?n:-n),balance:f.balance+(mode==='stake'?-n:n)}));}
 function manage(farm){show({eyebrow:'EXAMPLE POSITION · NO REAL FUNDS',title:farm.pair,body:<FarmForm farm={farm} onUpdate={update}/>,actions:<span className="jr-note">For interface review only.</span>});}
 function claim(farm){show({eyebrow:'PREVIEW REWARD FLOW',title:'Review your example rewards.',body:<><p>{farm.pair}</p><div className="jr-dialog-amount">{farm.jackEarned.toFixed(2)} JACK</div><p>+ {farm.pairEarned.toFixed(2)} {farm.earnToken}</p><DataNotice>No real tokens will be claimed.</DataNotice></>,actions:<><button className="jr-btn jr-btn-outline" onClick={close}>Cancel</button><button className="jr-btn jr-btn-dark" onClick={()=>{setRows(c=>c.map(f=>f.id===farm.id?{...f,jackEarned:0,pairEarned:0}:f));close();notify('Example rewards cleared. No tokens were transferred.');}}>Simulate claim <Icon/></button></>});}
 const totalStaked=rows.reduce((a,f)=>a+f.stakedLp,0);
 return <div className="jr-page"><div className="jr-container">
 <section className="jr-feature-hero jr-farm-hero"><div><span className="jr-eyebrow">LIQUIDITY FARMS / A PLACE TO GROW</span><h1>Plant liquidity.<br/><span>Track your position.</span></h1><p>A clearer home for your LP pools, reward pairs, and positions. Explore the farms and find the layout that works for you.</p><span className="jr-badge jr-badge-amber">Example pools · UI only</span></div><img src={rabbit} alt="Jack Rabbit relaxing above the farms"/></section>
 <div className="jr-stats"><article className="jr-kpi"><span className="jr-round-icon"><Icon name="leaf"/></span><div><span>Pool layouts</span><strong>{rows.length}</strong><small>Preview pool collection</small></div></article><article className="jr-kpi"><span className="jr-round-icon"><Icon name="coin"/></span><div><span>Reward streams</span><strong>JACK + pair</strong><small>Example dual-token rewards</small></div></article><article className="jr-kpi"><span className="jr-round-icon"><Icon name="wallet"/></span><div><span>Your preview liquidity</span><strong>{totalStaked.toFixed(2)} LP</strong><small>Not a wallet balance</small></div></article><article className="jr-kpi"><span className="jr-round-icon"><Icon name="star"/></span><div><span>Saved pools</span><strong>{favorites.length}</strong><small>Your picks in this session</small></div></article></div>
 <div className="jr-toolbar"><div className="jr-tabs" role="group" aria-label="Filter farms">{[['all','All pools'],['staked','Staked'],['favorites','Saved']].map(([id,label])=><button key={id} className={filter===id?'active':''} aria-pressed={filter===id} onClick={()=>setFilter(id)}>{label}</button>)}</div><div className="jr-toolbar-group"><label className="jr-search"><Icon name="search" size={17}/><input aria-label="Search farm pools" placeholder="Search a pool…" value={search} onChange={e=>setSearch(e.target.value)}/></label><select className="jr-select" aria-label="Sort farm pools" value={sort} onChange={e=>setSort(e.target.value)}><option value="default">Featured pools</option><option value="name">Pool name</option><option value="apr">Example APR</option></select><div className="jr-tabs jr-view-tabs"><button aria-label="Grid view" aria-pressed={view==='grid'} className={view==='grid'?'active':''} onClick={()=>setView('grid')}><Icon name="grid" size={17}/></button><button aria-label="List view" aria-pressed={view==='list'} className={view==='list'?'active':''} onClick={()=>setView('list')}><Icon name="list" size={17}/></button></div></div></div>
 <DataNotice>All liquidity, APR, balances, and rewards below are example data. Manage a position to preview the form; no transaction is sent.</DataNotice>
 {!visible.length?<section className="jr-panel"><EmptyState icon={filter==='favorites'?'star':'leaf'} title={search?'No matching pools':filter==='staked'?'Your garden starts here.':'Save your first pool.'} action={<button className="jr-btn jr-btn-dark" onClick={()=>{setFilter('all');setSearch('');}}>Explore all pools <Icon/></button>}>{search?'Try a token symbol such as PLS, HEX, or JACK.':filter==='staked'?'Try a sample stake to explore how a position appears.':'Tap the star on a pool to keep it close.'}</EmptyState></section>:<div className={`jr-farms-grid ${view==='list'?'jr-farms-list':''}`}>{visible.map(f=><article className="jr-farm-card" key={f.id}><div className="jr-farm-card-top"><div className="jr-pair-icons"><img src={jack} alt="JACK"/><img src={TOKEN_META[f.token].icon} alt={f.earnToken}/></div><div><h2>{f.pair}</h2><span>Earn JACK + {f.earnToken}</span></div><button className={`jr-icon-btn jr-save-pool ${favorites.includes(f.id)?'saved':''}`} aria-label={`${favorites.includes(f.id)?'Unsave':'Save'} ${f.pair}`} aria-pressed={favorites.includes(f.id)} onClick={()=>setFavorites(a=>a.includes(f.id)?a.filter(id=>id!==f.id):[...a,f.id])}><Icon name="star" size={18}/></button></div><div className="jr-farm-numbers"><div><span>Example APR <Icon name="info" size={12}/></span><strong>{f.apr}</strong></div><div><span>Example pool value</span><strong>{f.poolValue}</strong></div></div><div className="jr-farm-position"><div><span>Preview staked</span><strong>{f.stakedLp.toFixed(2)} LP</strong></div><div><span>Example rewards</span><strong>{f.jackEarned.toFixed(2)} <small>JACK</small></strong><small>+ {f.pairEarned.toFixed(2)} {f.earnToken}</small></div></div><div className="jr-farm-actions"><button className="jr-btn jr-btn-dark" onClick={()=>manage(f)}>Manage position <Icon size={16}/></button><button className="jr-btn jr-btn-outline" onClick={()=>claim(f)} disabled={f.jackEarned===0&&f.pairEarned===0}>Claim</button></div><span className="jr-pool-footnote"><Icon name="shield" size={12}/> Preview only. Contract integration pending.</span></article>)}</div>}
 <section className="jr-farms-bottom"><div><Icon name="book"/><h3>New to liquidity pools?</h3><p>Understand the position and its risks before committing any tokens.</p><button className="jr-text-link" onClick={()=>show({title:'Know your position.',eyebrow:'LIQUIDITY POOL GUIDE',body:<><p>A liquidity position represents participation in a token pair. The actual pool contract determines deposits, withdrawals, fees, and rewards.</p><p>Review token addresses, approval amounts, market exposure, and withdrawal conditions before using a live pool. The values in this preview are examples only.</p></>})}>Read the pool guide <Icon size={16}/></button></div><div><Icon name="shield"/><h3>Follow the protocol.</h3><p>Explore the Treasury for the other side of the ecosystem.</p><Link to="/treasury/vault" className="jr-text-link">Explore the vault <Icon size={16}/></Link></div></section>
 </div></div>;
}
