import React from "react";
import {Link} from "react-router-dom";
import Icon from "../ui/Icon";
import {SocialLinks} from "../ui/SiteFooter";
import hero from "../assets/richrabbit.png";
import mine from "../assets/jack-mining.png";
import stake from "../assets/banner-carrots.png";
import bond from "../assets/jackfallingrabbithole.png";
import treasury from "../assets/jackchest.png";
import rocket from "../assets/Jackriding.png";
import logo from "../assets/jacklogo.png";
const modules=[
 {title:"Stake your conviction.",tag:"01 / STAKING",text:"Explore external-token pools or stake JACK to follow the other side of the reward loop.",to:"/stake",link:"Explore staking",image:stake,tone:"green"},
 {title:"Make your next move.",tag:"02 / MINING",text:"Discover weekly mining windows, participation points, and your reward journey.",to:"/mining",link:"Enter the mine",image:mine,tone:"orange"},
 {title:"Put time on your side.",tag:"03 / BOND NFTS",text:"Explore pDAI bond terms and keep your positions together in one collectible view.",to:"/nfts",link:"Explore bonds",image:bond,tone:"gold"},
 {title:"Follow the value.",tag:"04 / TREASURY",text:"A clearer view of the reserves, holdings, and activity at the heart of the ecosystem.",to:"/treasury",link:"Open the treasury",image:treasury,tone:"cream"},
];
const faqs=[
 ['What is Jack Rabbit?','Jack Rabbit is a community-powered DeFi project on PulseChain. The interface brings staking, mining, liquidity farming, bond NFTs, and treasury visibility into one ecosystem.'],
 ['What can I do in this preview?','Explore every screen, try filters and forms, and review example positions. Pages marked as sample data are demonstrations. This preview does not send transactions or represent real balances.'],
 ['How does the pDAI mission fit in?','The project aims to build protocol value and reserves that can support pDAI over time. A peg is a goal, not a guarantee. The final contracts and their verified configuration determine actual behavior.'],
 ['Do I need a wallet to explore?','No. The UI preview is available without a wallet. A verified network, wallet connection, and completed contract integration will be required for actual participation.'],
 ['Where can I find official community links?','The community section below includes X, Telegram, Discord, Medium, and GitHub. Only confirmed destinations are enabled; pending accounts are clearly identified to avoid impersonation links.'],
];
export default function LandingExperience(){return <div className="jr-home">
 <section className="jr-home-hero"><div className="jr-container jr-hero-grid"><div className="jr-hero-copy"><span className="jr-eyebrow jr-pill"><span className="jr-dot"/> THE PULSECHAIN BURROW</span><h1>Small rabbit.<br/><span>Big mission.</span></h1><p>More than a token. A whole ecosystem.<br/>Stake, mine, farm, and find your place in the world of JACK.</p><div className="jr-button-row"><Link to="/stake" className="jr-btn jr-btn-dark">Explore the dApp <Icon/></Link><a href="#ecosystem" className="jr-btn jr-btn-ghost">Meet the ecosystem <Icon name="chevron"/></a></div><div className="jr-hero-footnote"><span className="jr-mini-logo"><img src={logo} alt=""/></span><div><strong>Born to burn. Built for the burrow.</strong><small>Community spirit. A long-term pDAI mission.</small></div></div></div>
 <div className="jr-hero-art"><div className="jr-hero-orbit"/><span className="jr-art-star jr-star-one">✦</span><span className="jr-art-star jr-star-two">✧</span><span className="jr-art-label">100% JACK ENERGY</span><img src={hero} alt="Jack Rabbit relaxing on a cloud, wearing sunglasses" fetchPriority="high"/><div className="jr-art-note"><Icon name="leaf"/><div><strong>Welcome to the burrow.</strong><span>There’s a path for everyone.</span></div></div><span className="jr-art-caption">EST. ON PULSECHAIN ↗</span></div></div></section>
 <div className="jr-word-strip" aria-label="Ecosystem areas"><div className="jr-container"><span>STAKE</span><b>✦</b><span>MINE</span><b>✦</b><span>FARM</span><b>✦</b><span>BOND</span><b>✦</b><span>BUILD THE BURROW</span></div></div>
 <section id="ecosystem" className="jr-section jr-container"><div className="jr-section-heading"><div><span className="jr-eyebrow">ONE ECOSYSTEM. DIFFERENT WAYS IN.</span><h2>Find your next rabbit hole.</h2></div><p>Choose your path. Get to know the mechanics.<br/>Make the burrow your own.</p></div><div className="jr-ecosystem-grid">{modules.map(m=><Link to={m.to} key={m.to} className={`jr-ecosystem-card jr-tone-${m.tone}`}><span className="jr-eyebrow">{m.tag}</span><img src={m.image} alt="" loading="lazy"/><h3>{m.title}</h3><p>{m.text}</p><span className="jr-card-link">{m.link}<Icon/></span></Link>)}</div><Link to="/farms" className="jr-farm-callout"><span className="jr-round-icon"><Icon name="leaf"/></span><div><strong>More of a grower?</strong><span>Explore liquidity farms and put your LP position in focus.</span></div><span className="jr-card-link">Discover farms <Icon/></span></Link></section>
 <section id="how-it-works" className="jr-mission-section"><div className="jr-container jr-mission-grid"><div className="jr-mission-art"><img src={rocket} alt="Jack riding a rocket" loading="lazy"/><span className="jr-mission-stamp">THE BIGGER<br/>PICTURE ↗</span></div><div><span className="jr-eyebrow">NOT JUST MOVEMENT. MOMENTUM.</span><h2>Built to keep<br/><em>value moving.</em></h2><p>Participation is where the story starts. JACK’s mission is to connect ecosystem activity, protocol reserves, and long-term pDAI support.</p><div className="jr-flow-list">{[['01','Participate','Stake, mine, farm, or explore a bond.'],['02','Strengthen the burrow','Follow how protocol activity connects to its treasury.'],['03','Support the mission','Build toward the pDAI goal, with progress you can inspect.']].map(([n,t,d])=><div key={n}><span>{n}</span><section><h3>{t}</h3><p>{d}</p></section></div>)}</div><Link to="/treasury" className="jr-text-link">Look inside the treasury <Icon/></Link></div></div></section>
 <section className="jr-section jr-container"><div className="jr-section-heading"><div><span className="jr-eyebrow">NEW AROUND HERE?</span><h2>Your first hop, made simple.</h2></div><Link to="/swap" className="jr-btn jr-btn-outline">Explore the swap <Icon/></Link></div><div className="jr-three-grid">{[['wallet','Bring your wallet','Use a compatible wallet and verify that you are on the intended PulseChain network.'],['search','Know what you’re using','Review the token, contract address, route, and any transaction costs before continuing.'],['shield','Review every step','Check the amount and minimum received. Only sign when you understand the transaction.']].map(([i,t,d],n)=><article className="jr-step-card" key={t}><div><span className="jr-round-icon"><Icon name={i}/></span><span className="jr-step-number">0{n+1}</span></div><h3>{t}</h3><p>{d}</p></article>)}</div><p className="jr-small-disclaimer"><Icon name="info" size={15}/> Swap configuration and financial integrations are being verified. This is not a live trading release.</p></section>
 <section id="roadmap" className="jr-roadmap-section"><div className="jr-container"><div className="jr-section-heading"><div><span className="jr-eyebrow">THE JOURNEY, NOT A PROMISE</span><h2>Growing the burrow.</h2></div><p>A clear direction. One carefully verified step at a time.</p></div><div className="jr-roadmap-grid">{[['01','Build the experience','CURRENT FOCUS','Complete the interface, connect the journeys, and make every screen easier to use.'],['02','Connect the ecosystem','NEXT','Verify contracts and network configuration, then complete each participation flow.'],['03','Test the whole loop','PLANNED','Exercise staking, mining, farms, bonds, and treasury reporting together.'],['04','Strengthen the mission','LONG-TERM','Develop the reserve strategy and assess progress toward pDAI support.']].map(([n,t,s,d])=><article key={n}><div className="jr-roadmap-line"><span>{n}</span><i/></div><small>{s}</small><h3>{t}</h3><p>{d}</p></article>)}</div><Link to="/story" className="jr-text-link">Explore Jack’s illustrated story & original roadmap <Icon/></Link></div></section>
 <section id="faq" className="jr-section jr-container jr-faq-grid"><div><span className="jr-eyebrow">A LITTLE CLARITY GOES A LONG WAY</span><h2>Before you<br/>jump in.</h2><p>Get to know JACK, the preview,<br/>and the bigger mission.</p><span className="jr-faq-doodle" aria-hidden="true">?</span></div><div className="jr-faq-list">{faqs.map(([q,a],i)=><details key={q} open={i===0?true:undefined}><summary>{q}<Icon name="chevron"/></summary><p>{a}</p></details>)}</div></section>
 <section id="community" className="jr-container jr-community-section"><div><span className="jr-eyebrow">GOOD COMPANY. BIG IDEAS.</span><h2>The burrow is better<br/><span>with you in it.</span></h2><p>Follow the build, share your ideas, and find your fellow rabbits.<br/>One community. A shared mission.</p><SocialLinks large/><p className="jr-community-note">Official community accounts are awaiting confirmation. GitHub is available now.</p></div><div className="jr-community-brand" aria-hidden="true"><img src={logo} alt=""/><span>STAY JACK.</span></div></section>
 </div>;}
