import React,{useMemo,useState} from "react";
import {Link} from "react-router-dom";
import {parseUnits,formatUnits} from "ethers";
import useTreasuryData from "../hooks/useTreasuryData";
import Icon from "../ui/Icon";
import {DataNotice,EmptyState,IS_UI_PREVIEW,PageHeading,useUi} from "../ui/UiContext";
import jack from "../assets/jacklogo.png";
import pls from "../assets/pls.svg";
import plsx from "../assets/plsx.svg";
import pdai from "../assets/pdai.svg";
import chest from "../assets/jackchest.png";
const icons={JACK:jack,PLS:pls,PLSX:plsx,pDAI:pdai};
// Illustrative data is isolated from contract reads and clearly labelled in every view.
const example={treasuryJack:'1,250,000 JACK',pdaiTreasuryBalance:'480,000 pDAI',pdaiTreasuryReserves:'420,000 pDAI',supply:'1,000,000,000 JACK',burned:'25,000 JACK',circulating:'Not calculated',mintable:'15,000 JACK',feePct:'1.0000%',burnSharePct:'40.00%',feeMode:'Example dynamic',manualExpiry:'Not active',treasuryTarget:'2,000,000 JACK',loanOutstanding:'85,000 JACK',loanRepaid:'12,400 JACK',loanRequestable:'Not calculated',jackIncome5Y:'165,200 JACK',todayNet:'420 JACK',pdaiIncome5Y:'62,000 pDAI',pdaiReservesIn:'500,000 pDAI',pdaiReservesOut:'80,000 pDAI'};
const holdings=[{symbol:'JACK',name:'Jack Rabbit',actual:'1,250,000',tracked:'1,250,000',usable:'1,165,000',addrShort:'Example holding'},{symbol:'pDAI',name:'Pulse DAI',actual:'480,000',tracked:'480,000',usable:'60,000',addrShort:'Example protected reserve'},{symbol:'PLSX',name:'PulseX',actual:'8,420,000',tracked:'8,400,000',usable:'8,420,000',addrShort:'Example holding'}];
const lps=[{symbol:'JACK / PLS',name:'Example liquidity position',bal:'12,450',addrShort:'Example LP'},{symbol:'JACK / PLSX',name:'Example liquidity position',bal:'8,200',addrShort:'Example LP'}];
const events=[{ev:'PdaiReserveDeposited',c:'Treasury',d:'Example pDAI reserve deposit',block:'Sample',category:'income'},{ev:'TokenSwapped',c:'Treasury',d:'Example token-to-JACK swap',block:'Sample',category:'swap'},{ev:'LoanRepaid',c:'Treasury',d:'Example loan repayment',block:'Sample',category:'loan'},{ev:'HoldingsSynced',c:'Treasury',d:'Example holdings synchronization',block:'Sample',category:'vault'},{ev:'PdaiReserveSent',c:'Treasury',d:'Example pDAI reserve outflow',block:'Sample',category:'outflow'},{ev:'Burn',c:'JACK token',d:'Example JACK burn event',block:'Sample',category:'burn'}];
function Kpi({icon,label,value,note}){return <article className="jr-kpi"><span className="jr-round-icon"><Icon name={icon}/></span><div><span>{label}</span><strong>{value??'—'}</strong><small>{note||'Verify against network data'}</small></div></article>;}
function Readout({title,icon,rows}){return <section className="jr-panel"><div className="jr-panel-header"><h2>{title}</h2><Icon name={icon}/></div><dl className="jr-summary-list">{rows.map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value??'—'}</dd></div>)}</dl></section>;}
export default function TreasuryExperience({view='overview'}){
 const data=useTreasuryData();const {notify,show}=useUi();const [examples,setExamples]=useState(IS_UI_PREVIEW);
 const labels={overview:['The heart of the burrow.','An organized view of protocol reserves, token readouts, and treasury activity.'],burn:['Every movement, made clearer.','Explore the fee split and review how a transfer could flow through the ecosystem.'],vault:['Know what’s in the vault.','Review holding tokens, usable balances, and protocol-owned liquidity.'],activity:['Follow the trail.','A readable ledger of the activity behind the ecosystem.']};
 const o=examples?example:data.overview;const ready=examples||Boolean(data.readProvider&&data.configReady);
 function load(kind){if(examples){notify('Showing illustrative data. Switch off examples for network reads.');return;}if(!ready){show({eyebrow:'READ-ONLY CONNECTION',title:'Network data is not connected.',body:<p>A verified RPC and contract configuration are required. No wallet action is needed to explore the example interface.</p>});return;}(kind==='events'?data.loadEvents:kind==='vault'?data.refreshVault:data.refreshAll)();}
 return <div className="jr-page"><div className="jr-container"><PageHeading eyebrow={`TREASURY / ${view==='burn'?'BURN ENGINE':view.toUpperCase()}`} title={labels[view][0]} description={labels[view][1]} action={<button className="jr-btn jr-btn-outline" onClick={()=>setExamples(!examples)}>{examples?'Hide example data':'Show example data'}<Icon name="grid" size={16}/></button>}/><DataNotice>{examples?'Illustrative treasury data for UI review. These are not actual protocol balances, rates, or events.':IS_UI_PREVIEW?'Network reads are disabled in this UI preview. Show example data to explore the layouts.':data.globalStatus}</DataNotice>
 {view==='overview'&&<OverviewPanel o={o} ready={ready} examples={examples} onRefresh={()=>load('overview')}/>}{view==='burn'&&<BurnPanel o={o} ready={ready} examples={examples} computed={data.computed}/>}{view==='vault'&&<VaultPanel holdings={examples?holdings:data.holdingsRows} lps={examples?lps:data.lpRows} examples={examples} onRefresh={()=>load('vault')}/>}{view==='activity'&&<ActivityPanel rows={examples?events:data.eventsRows} examples={examples} onRefresh={()=>load('events')} status={data.eventsStatus}/>}</div></div>;
}
function OverviewPanel({o,ready,examples,onRefresh}){
 const v=k=>ready?o[k]:'—';
 return <><div className="jr-stats"><Kpi icon="coin" label="Treasury JACK" value={v('treasuryJack')} note={examples?'Example reserve balance':'Loaded contract balance'}/><Kpi icon="shield" label="Protected pDAI reserve" value={v('pdaiTreasuryReserves')} note={examples?'Example protected allocation':'Reserve accounting readout'}/><Kpi icon="leaf" label="Fee setting" value={v('feePct')} note={examples?'Illustrative fee only':'Requires verified token ABI'}/><Kpi icon="clock" label="Protocol phase" value="Not verified" note="Not inferred from a balance"/></div>
 <div className="jr-two-column"><section className="jr-panel jr-treasury-intro"><div><span className="jr-eyebrow">THE ECOSYSTEM’S ACCOUNTING HOME</span><h2>Value in view.<br/>Nothing behind the curtain.</h2><p>Explore the holdings, inspect the fee model, and follow the recorded activity. Every readout should have a verifiable source.</p><div className="jr-button-row"><Link className="jr-btn jr-btn-dark" to="/treasury/vault">Open the vault <Icon/></Link><button className="jr-btn jr-btn-outline" onClick={onRefresh}><Icon name="refresh" size={16}/> Refresh</button></div></div><img src={chest} alt="Jack Rabbit treasury chest"/></section><Readout title="Reserve snapshot" icon="shield" rows={[["JACK balance",v('treasuryJack')],["pDAI wallet balance",v('pdaiTreasuryBalance')],["Protected pDAI",v('pdaiTreasuryReserves')],["Treasury target",v('treasuryTarget')]]}/></div>
 <div className="jr-three-grid jr-dashboard-grid"><Readout title="JACK token" icon="coin" rows={[["Supply",v('supply')],["Burn counter",v('burned')],["Mintable readout",v('mintable')],["Fee mode",v('feeMode')]]}/><Readout title="Treasury inflows" icon="arrow" rows={[["JACK income window",v('jackIncome5Y')],["Today’s JACK income",v('todayNet')],["pDAI income window",v('pdaiIncome5Y')]]}/><Readout title="Protected reserves" icon="lock" rows={[["Reserve deposits",v('pdaiReservesIn')],["Reserve outflows",v('pdaiReservesOut')],["Outstanding loan",v('loanOutstanding')]]}/></div>
 <section className="jr-next-step"><Icon name="info"/><p>{examples?'Illustrative values demonstrate the layout. They do not establish protocol health, solvency, or a pDAI peg.':'Readouts depend on the configured RPC, contract deployment, and matching ABI. Missing data must not be treated as zero.'}</p><Link className="jr-text-link" to="/treasury/activity">Follow the activity <Icon size={16}/></Link></section></>;
}
function BurnPanel({o,ready,examples,computed}){
 const [amount,setAmount]=useState('1000');const [fee,setFee]=useState('1');const [share,setShare]=useState('40');
 const simulation=useMemo(()=>{try{if(!amount||!fee||!share)return {error:'Complete all three fields.'};const a=parseUnits(amount,18),f=parseUnits(fee,7),s=parseUnits(share,2);if(a<=0n||f<0n||f>1000000000n||s<0n||s>10000n)return {error:'Use a positive amount and percentages between 0 and 100.'};const paid=a*f/1000000000n;const burned=paid*s/10000n;const text=n=>Number(formatUnits(n,18)).toLocaleString(undefined,{maximumFractionDigits:6});return {fee:text(paid),burn:text(burned),treasury:text(paid-burned),net:text(a-paid)};}catch{return {error:'Enter valid decimal values. Amount: up to 18 decimals; fee: 7; burn share: 2.'};}},[amount,fee,share]);
 const edit=setter=>e=>/^\d*\.?\d*$/.test(e.target.value)&&setter(e.target.value);
 return <><div className="jr-stats"><Kpi icon="coin" label="Fee readout" value={ready?o.feePct:'—'}/><Kpi icon="leaf" label="Burn share of fee" value={ready?o.burnSharePct:'—'}/><Kpi icon="shield" label="Loan outstanding" value={ready?o.loanOutstanding:'—'}/><Kpi icon="check" label="Loan repaid" value={ready?o.loanRepaid:'—'}/></div>
 <div className="jr-two-column"><section className="jr-panel"><div className="jr-panel-header"><div><h2>Explore a transfer.</h2><p>An illustrative calculator. No tokens are moved.</p></div><span className="jr-badge jr-badge-amber">Simulation</span></div><label className="jr-field-label" htmlFor="jr-sim-amount">Transfer amount</label><div className="jr-input-box"><div className="jr-amount-row"><input id="jr-sim-amount" inputMode="decimal" value={amount} onChange={edit(setAmount)}/><span className="jr-token-pill"><img src={jack} alt=""/>JACK</span></div></div><div className="jr-simulation-fields"><label>Illustrative fee (%)<input className="jr-text-input" aria-label="Illustrative fee percentage" inputMode="decimal" value={fee} onChange={edit(setFee)}/></label><label>Burn share of fee (%)<input className="jr-text-input" aria-label="Burn share percentage" inputMode="decimal" value={share} onChange={edit(setShare)}/></label></div>
 {simulation.error?<p className="jr-error-text" role="alert">{simulation.error}</p>:<div className="jr-simulation-results">{[['Transfer fee',simulation.fee],['JACK burned',simulation.burn],['To treasury',simulation.treasury],['Recipient receives',simulation.net]].map(([label,value])=><div key={label}><span>{label}</span><strong>{value} <small>JACK</small></strong></div>)}</div>}<div className="jr-button-row"><button className="jr-btn jr-btn-outline" onClick={()=>{setAmount('1000');setFee('1');setShare('40');}}>Reset example <Icon name="refresh" size={16}/></button><button className="jr-btn jr-btn-dark" disabled={!ready||examples} onClick={()=>{setFee(String(parseFloat(computed.feePctStr)||0));setShare(String(parseFloat(computed.burnPctStr)||0));}}>Use loaded rates <Icon size={16}/></button></div><DataNotice>Manual percentages model a simple fee split. Actual token behavior, exemptions, and burn limits require the verified contract.</DataNotice></section>
 <aside className="jr-stack"><section className="jr-panel jr-how-panel"><span className="jr-eyebrow">UNDERSTAND THE SPLIT</span><h2>One fee. Two destinations.</h2><div className="jr-split-visual"><span style={{flex:Math.max(0,Math.min(100,Number(share)||0))}}/><i style={{flex:100-Math.max(0,Math.min(100,Number(share)||0))}}/></div><div className="jr-split-legend"><span>Burn share <strong>{Number.isFinite(Number(share))?Math.min(100,Math.max(0,Number(share))):0}%</strong></span><span>Treasury share <strong>{100-Math.min(100,Math.max(0,Number(share)||0))}%</strong></span></div><p>The percentages above divide the fee, not the entire transfer. The recipient gets the transfer amount minus that fee in this simplified example.</p></section><Readout title="Reference readouts" icon="book" rows={[["Treasury balance",ready?o.treasuryJack:'—'],["Treasury target",ready?o.treasuryTarget:'—'],["Fee mode",ready?o.feeMode:'—'],["Override expiry",ready?o.manualExpiry:'—']]}/></aside></div></>;
}
function VaultPanel({holdings,lps,examples,onRefresh}){
 const {previewAction}=useUi();const [search,setSearch]=useState('');
 const rows=holdings.filter(r=>`${r.symbol} ${r.name}`.toLowerCase().includes(search.toLowerCase()));
 function difference(a,b){try{return Number(formatUnits(parseUnits(String(a).replace(/,/g,''),18)-parseUnits(String(b).replace(/,/g,''),18),18)).toLocaleString(undefined,{maximumFractionDigits:6});}catch{return '—';}}
 return <><div className="jr-stats"><Kpi icon="coin" label="Holding tokens loaded" value={holdings.length} note={examples?'Example token collection':'Only the loaded collection'}/><Kpi icon="leaf" label="LP positions loaded" value={lps.length} note={examples?'Example LP collection':'Only the loaded collection'}/><Kpi icon="shield" label="Data source" value={examples?'Illustrative':'Contract reads'} note="Not a solvency assessment"/><Kpi icon="refresh" label="Synchronization" value="Review required" note="No transaction is automatic"/></div>
 <section className="jr-panel"><div className="jr-panel-header"><div><h2>Holding tokens</h2><p>Wallet, recorded, and usable balances side by side.</p></div><div className="jr-button-row"><button className="jr-btn jr-btn-outline jr-btn-small" onClick={onRefresh}><Icon name="refresh" size={16}/> Refresh</button><button className="jr-btn jr-btn-dark jr-btn-small" onClick={()=>previewAction('Sync holdings — integration pending')}>Sync holdings <Icon size={16}/></button></div></div><div className="jr-toolbar"><label className="jr-search"><Icon name="search" size={16}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Find a holding token…" aria-label="Search treasury holdings"/></label><span className="jr-note">{rows.length} tokens shown</span></div>
 {!rows.length?<EmptyState icon="coin" title={search?'No matching token.':'No holdings loaded.'}>{search?'Try a different symbol or token name.':'Connect a verified read-only data source or enable examples above.'}</EmptyState>:<div className="jr-table-scroll"><table className="jr-table"><thead><tr><th>Token</th><th>Wallet balance</th><th>Recorded</th><th>Available</th><th>Available − recorded</th></tr></thead><tbody>{rows.map((r,i)=><tr key={r.addr||i}><td><div className="jr-table-identity">{icons[r.symbol]?<img src={icons[r.symbol]} alt=""/>:<span className="jr-round-icon"><Icon name="coin"/></span>}<div><strong>{r.symbol}</strong><small>{r.name}</small></div></div></td><td>{r.actual}</td><td>{r.tracked}</td><td><strong>{r.usable}</strong></td><td>{difference(r.usable,r.tracked)}</td></tr>)}</tbody></table></div>}<p className="jr-form-note">Amounts use the token’s displayed units. A difference is not, by itself, a loss or a pending transaction.</p></section>
 <section className="jr-panel jr-dashboard-grid"><div className="jr-panel-header"><div><h2>Protocol-owned liquidity</h2><p>LP balances held by the configured Treasury.</p></div><Icon name="leaf"/></div>{!lps.length?<EmptyState icon="leaf" title="No LP positions loaded.">A verified LP collection will appear here.</EmptyState>:<div className="jr-lp-grid">{lps.map((r,i)=><article className="jr-lp-card" key={r.addr||i}><span className="jr-round-icon"><Icon name="leaf"/></span><div><h3>{r.symbol}</h3><p>{r.name}</p></div><strong>{r.bal}<small>LP units</small></strong></article>)}</div>}<Link className="jr-text-link" to="/farms">Explore the farms <Icon size={16}/></Link></section></>;
}
function ActivityPanel({rows,examples,onRefresh,status}){
 const {show}=useUi();const [filter,setFilter]=useState('all');const [search,setSearch]=useState('');const [page,setPage]=useState(0);
 function category(r){if(r.category)return r.category;const n=String(r.ev||'').toLowerCase();return n.includes('swap')?'swap':n.includes('loan')?'loan':n.includes('sent')?'outflow':n.includes('income')||n.includes('deposit')?'income':n.includes('burn')?'burn':'vault';}
 const filtered=rows.filter(r=>(filter==='all'||category(r)===filter)&&`${r.ev} ${r.c} ${r.d} ${r.block}`.toLowerCase().includes(search.toLowerCase()));const pages=Math.max(1,Math.ceil(filtered.length/8));const current=Math.min(page,pages-1);const visible=filtered.slice(current*8,current*8+8);
 function details(r){show({eyebrow:examples?'EXAMPLE EVENT':'LOADED EVENT',title:String(r.ev).replace(/([a-z])([A-Z])/g,'$1 $2'),body:<><p>{r.d}</p><dl className="jr-summary-list"><div><dt>Source</dt><dd>{r.c}</dd></div><div><dt>Block</dt><dd>{r.block}</dd></div><div><dt>Transaction hash</dt><dd>{r.transactionHash||'Not supplied by this data source'}</dd></div></dl><DataNotice>{examples?'This is an illustrative activity record, not a transaction.':'This list covers only the events returned by the configured loader.'}</DataNotice></>});}
 return <><div className="jr-stats">{[['book','Events loaded',rows.length],['arrow','Incoming',rows.filter(r=>category(r)==='income').length],['external','Outgoing',rows.filter(r=>category(r)==='outflow').length],['refresh','Swaps',rows.filter(r=>category(r)==='swap').length]].map(([icon,label,value])=><Kpi key={label} icon={icon} label={label} value={value} note={examples?'Example event window':'Loaded event window only'}/>)}</div><section className="jr-panel"><div className="jr-panel-header"><div><h2>The activity ledger</h2><p>A closer look at the movements behind the numbers.</p></div><button className="jr-btn jr-btn-dark jr-btn-small" disabled={String(status).startsWith('Loading')} onClick={onRefresh}><Icon name="refresh" size={16}/> Load events</button></div><div className="jr-toolbar"><div className="jr-tabs jr-activity-tabs">{[['all','All activity'],['income','Incoming'],['outflow','Outgoing'],['swap','Swaps'],['loan','Loans'],['vault','Vault']].map(([id,label])=><button key={id} className={filter===id?'active':''} onClick={()=>{setFilter(id);setPage(0);}} aria-pressed={filter===id}>{label}</button>)}</div><label className="jr-search"><Icon name="search" size={16}/><input aria-label="Search treasury events" placeholder="Search events…" value={search} onChange={e=>{setSearch(e.target.value);setPage(0);}}/></label></div>
 {!visible.length?<EmptyState icon="book" title={rows.length?'No matching activity.':'No events loaded yet.'}>{rows.length?'Try another filter or search term.':'Load the configured event window, or use example data to review the interface.'}</EmptyState>:<div className="jr-table-scroll"><table className="jr-table"><thead><tr><th>Activity</th><th>Source</th><th>Details</th><th>Block</th><th><span className="jr-sr-only">Inspect</span></th></tr></thead><tbody>{visible.map((r,i)=><tr key={`${r.block}-${r.ev}-${i}`}><td><div className="jr-table-identity"><span className="jr-round-icon"><Icon name={category(r)==='swap'?'refresh':category(r)==='outflow'?'external':'arrow'} size={18}/></span><div><strong>{String(r.ev).replace(/([a-z])([A-Z])/g,'$1 $2')}</strong><small>{category(r)}</small></div></div></td><td>{r.c}</td><td>{r.d}</td><td>{r.block}</td><td><button className="jr-icon-btn" aria-label={`View ${r.ev} details`} onClick={()=>details(r)}><Icon name="arrow" size={16}/></button></td></tr>)}</tbody></table></div>}
 <div className="jr-table-footer"><span>{filtered.length} {examples?'example':'loaded'} events</span><nav className="jr-pagination" aria-label="Activity pagination"><button className="jr-icon-btn" disabled={current===0} onClick={()=>setPage(Math.max(0,current-1))} aria-label="Previous events">←</button><span>{current+1} / {pages}</span><button className="jr-icon-btn" disabled={current+1>=pages} onClick={()=>setPage(Math.min(pages-1,current+1))} aria-label="Next events">→</button></nav></div>{!examples&&status&&<p className="jr-form-note" role="status">{status}</p>}</section><section className="jr-next-step"><Icon name="info"/><p>Only the loaded event window is displayed. Events missing from the current contract interfaces and calls that emit no events cannot be reconstructed by this view.</p></section></>;
}
