export const JACK = '0xc8777079d6f8b490996f3f9dc35c2155ce1875ec';
export const PDAI = '0x6b175474e89094c44da98b954eedeac495271d0f';
export const CHART = 'https://www.geckoterminal.com/pulsechain/pools/0x7ef0d4194c9c9ba874fdfb9586e296a3e4ec72d2';
export const EXPLORER = 'https://scan.pulsechain.com/address/';
// No ecosystem deployments have been verified. Never substitute the legacy demo addresses.
export const modules = [
  { id: 'diamond', label: 'Diamond Hands', mark: '◆', verb: 'HOLD TIGHT.\nEARN JACK.', blurb: 'Put your favourite tokens to work. Eligible external-token stakers share funded JACK emissions.', action: 'Stake tokens', reward: 'JACK', source: 'Dedicated JACK incentive reserve', requirement: 'Verified Stake deployment, active pools and funded rewards', facts: [['Entry fee', '5% of received tokens'], ['Principal', '95% remains your stake'], ['Rewards', 'Variable, reserve-funded']], steps: ['Choose an active pool', 'Review fees and deposit', 'Claim JACK or withdraw your stake'], note: 'The planned 50,550,000 JACK allocation is a founder seed commitment, not a confirmed on-chain reserve.' },
  { id: 'jackies', label: 'Jackies', mark: '✦', verb: 'JACK IN.\nMORE OUT.', blurb: 'Stake JACK to share external-token rewards funded by participation in the ecosystem.', action: 'Stake JACK', reward: 'External tokens', source: 'External staking fees and eligible reward injections', requirement: 'Verified Stake deployment and funded reward streams', facts: [['Entry fee', '5% of received JACK'], ['Treasury share', '2.5% of received JACK'], ['Mining share', '2.5% to the configured sink']], steps: ['Stake your JACK', 'Accrue funded token rewards', 'Claim rewards or unstake'], note: 'A reward stream can be empty. Staking JACK does not guarantee an APY or a dollar return.' },
  { id: 'farm', label: 'Farm', mark: '❋', verb: 'PLANT LIQUIDITY.\nGROW CARROTS.', blurb: 'Bring eligible LP tokens. Harvest JACK and paired-token rewards from explicitly funded pools.', action: 'Deposit LP tokens', reward: 'JACK + paired token', source: 'Reviewed allocations to Farm reward streams', requirement: 'Verified Farm deployment, eligible LPs and reward funding', facts: [['LP entry fee', '5% by default'], ['Reward streams', 'JACK + paired token'], ['Principal', '95% remains withdrawable LP']], steps: ['Choose a funded LP pool', 'Deposit eligible LP tokens', 'Harvest rewards or withdraw'], note: 'Providing liquidity carries market and impermanent-loss risk. Reward amounts depend on actual funding and pool participation.' },
  { id: 'mining', label: 'Mining', mark: 'ϟ', verb: 'DIG IN.\nGO FULL RABBIT.', blurb: 'Deploy miners in funded rounds. Time-weighted points determine your share of economically unlocked JACK.', action: 'Deploy a miner', reward: 'Unlocked JACK', source: 'Organic JACK funding; earned Treasury credit in later rounds', requirement: 'Verified Mining deployment, funding and healthy price observations', facts: [['Round length', '7 days by default'], ['Payment split', '10% admin · 90% Treasury'], ['Reward unlock', 'Depends on round revenue']], steps: ['Wait for a funded round', 'Pay to deploy and earn points', 'Claim during the following round'], note: 'Miner payments are spent, not withdrawable stake. The advertised pool can exceed the rewards actually unlocked.' },
  { id: 'barrow', label: 'Barrow', mark: '◈', verb: 'BURROW DEEP.\nPLAY THE LONG GAME.', blurb: 'Exchange pDAI for a funded JACK vesting bond. Your bond tracks its base allocation, bonus and claim deadline.', action: 'Open a bond', reward: 'Vesting JACK', source: 'Free promise and reward buckets, excluding existing liabilities', requirement: 'Verified Barrow deployment, funded coverage and a healthy oracle', facts: [['Vesting range', '90–1,825 days'], ['Claim grace', '30 days by default'], ['Backing', 'Required before a bond opens']], steps: ['Choose a vesting term', 'Review the backed JACK quote', 'Claim vested JACK before expiry'], note: 'pDAI is the PulseChain token, not a promise of $1 redemption. Bond terms and backing must be checked on-chain before purchase.' },
];
