import React from 'react';
import {render,screen,fireEvent,within,waitFor} from '@testing-library/react';
import {MemoryRouter,Routes,Route} from 'react-router-dom';
import {UiProvider} from './ui/UiContext';
import {PreviewPortfolioProvider} from './ui/PreviewPortfolio';
import Farms from './pages/FarmsExperience';
import Claims from './pages/ClaimsExperience';
import Mint from './pages/BondMintExperience';
import Bonds from './pages/BondPositionsExperience';
import Treasury from './pages/TreasuryExperience';
import Landing from './pages/LandingExperience';
import SiteFooter from './ui/SiteFooter';
import MiningView from './ui/MiningView';
jest.mock('./hooks/useTreasuryData',()=>({__esModule:true,default:()=>({overview:{},computed:{},holdingsRows:[],lpRows:[],eventsRows:[],eventsStatus:'',globalStatus:'Not connected',configReady:false,readProvider:null,refreshAll:jest.fn(),refreshVault:jest.fn(),loadEvents:jest.fn()})}));
function mount(path='/farms'){return render(<MemoryRouter initialEntries={[path]}><UiProvider><PreviewPortfolioProvider><Routes><Route path="/" element={<Landing/>}/><Route path="/farms" element={<Farms/>}/><Route path="/mining/claims" element={<Claims/>}/><Route path="/nfts" element={<Mint/>}/><Route path="/nfts/bonds" element={<Bonds/>}/><Route path="/treasury/burn" element={<Treasury view="burn"/>}/><Route path="/treasury/activity" element={<Treasury view="activity"/>}/></Routes><SiteFooter/></PreviewPortfolioProvider></UiProvider></MemoryRouter>);}
function click(name){fireEvent.click(screen.getByRole('button',{name,exact:true}));}
it('has a complete landing, FAQ, community section, and footer',()=>{mount('/');expect(screen.getByRole('heading',{name:/Small rabbit/})).toBeInTheDocument();expect(screen.getByRole('heading',{name:/Growing the burrow/})).toBeInTheDocument();expect(screen.getAllByRole('link',{name:'Jack Rabbit on GitHub'})).toHaveLength(2);expect(screen.getByText('What is Jack Rabbit?')).toBeInTheDocument();});
it('never sends an unconfirmed social link to an invented account',()=>{mount('/');fireEvent.click(screen.getAllByRole('button',{name:'Telegram: official link pending'})[0]);expect(screen.getByRole('dialog')).toHaveTextContent('has not been confirmed');fireEvent.keyDown(document,{key:'Escape'});expect(screen.queryByRole('dialog')).not.toBeInTheDocument();});
it('filters and saves farm pools, including an empty state',()=>{mount();click('Saved');expect(screen.getByRole('heading',{name:'Save your first pool.'})).toBeInTheDocument();click('All pools');click('Save JACK-PLS');click('Saved');expect(screen.getAllByRole('heading',{name:'JACK-PLS'})).toHaveLength(1);fireEvent.change(screen.getByLabelText('Search farm pools'),{target:{value:'no-such-pool'}});expect(screen.getByRole('heading',{name:'No matching pools'})).toBeInTheDocument();});
it('validates and simulates a farm position without wallet calls',()=>{mount();fireEvent.click(screen.getAllByRole('button',{name:'Manage position'})[0]);const dialog=screen.getByRole('dialog');fireEvent.change(within(dialog).getByLabelText(/LP amount/),{target:{value:'999'}});fireEvent.click(within(dialog).getByRole('button',{name:'Simulate stake'}));expect(within(dialog).getByRole('alert')).toBeInTheDocument();fireEvent.change(within(dialog).getByLabelText(/LP amount/),{target:{value:'2'}});fireEvent.click(within(dialog).getByRole('button',{name:'Simulate stake'}));expect(screen.queryByRole('dialog')).not.toBeInTheDocument();click('Staked');expect(screen.getAllByRole('heading',{name:/JACK-PLS$/})).toHaveLength(1);expect(screen.getAllByText('2.00 LP').length).toBeGreaterThan(0);});
it('connects the preview bond builder to the positions gallery',async()=>{mount('/nfts');click('Review bond');expect(screen.getByRole('dialog')).toHaveTextContent(/NO REAL DEPOSIT/i);click('Add preview bond');await waitFor(()=>expect(screen.getByRole('heading',{name:'Your bonds. Your timeline.'})).toBeInTheDocument());expect(screen.getAllByText(/^UI-\d+/).length).toBeGreaterThan(0);});
it('rejects invalid preview NFT recipients and records a valid example transfer',()=>{mount('/nfts/bonds');click('Transfer JB-1001');click('Simulate transfer');expect(screen.getByRole('alert')).toHaveTextContent('valid, non-zero');fireEvent.change(screen.getByLabelText('Recipient address'),{target:{value:'0x1111111111111111111111111111111111111111'}});click('Simulate transfer');click('History');expect(screen.getByText('Transferred')).toBeInTheDocument();});
it('moves a sample mining claim to history and prevents it remaining claimable',()=>{mount('/mining/claims');click('Ready to claim');fireEvent.click(screen.getAllByRole('button',{name:'Review claim'})[0]);click('Simulate claim');click('History');expect(screen.getByText('Preview claimed')).toBeInTheDocument();expect(screen.getByText('Miner #1235')).toBeInTheDocument();});
it('calculates the preview fee split and validates percentages',()=>{mount('/treasury/burn');expect(screen.getByText('990')).toBeInTheDocument();expect(screen.getByText('10')).toBeInTheDocument();expect(screen.getByText('4')).toBeInTheDocument();expect(screen.getByText('6')).toBeInTheDocument();fireEvent.change(screen.getByLabelText('Illustrative fee percentage'),{target:{value:'101'}});expect(screen.getByRole('alert')).toHaveTextContent('between 0 and 100');});
it('filters the treasury ledger and opens readable event details',()=>{mount('/treasury/activity');click('Outgoing');expect(screen.getByText('Example pDAI reserve outflow')).toBeInTheDocument();expect(screen.queryByText('Example token-to-JACK swap')).not.toBeInTheDocument();click('View PdaiReserveSent details');expect(screen.getByRole('dialog')).toHaveTextContent('not a transaction');});
it('blocks financial callbacks in UI preview before they execute',()=>{const send=jest.fn();render(<UiProvider><button data-transaction="stake" onClick={send}>Send stake</button></UiProvider>);click('Send stake');expect(send).not.toHaveBeenCalled();expect(screen.getByRole('dialog')).toHaveTextContent('A preview, not a transaction.');});
it('does not enable an empty mining contribution',()=>{render(<MemoryRouter><UiProvider><MiningView amount="" setAmount={jest.fn()} currentWeek={null} loading={false} checkingAllowance={false} handleDeploy={jest.fn()} handleSyncWeek={jest.fn()} handleTryFunding={jest.fn()}/></UiProvider></MemoryRouter>);expect(screen.getByRole('button',{name:'Review deployment'})).toBeDisabled();});
